<?php $view->extend('layout.phtml') ?>
<?php $view['slots']->set('section', $section) ?>

<?php $view['slots']->start('styles') ?>
<style>
    .home .logo {
        display: none;
    }
</style>
<?php $view['slots']->stop() ?>

<div class="main-title">
    <img src="/assets/images/bg.svg" />
    <div class="glitch" data-text="La portería vertical">La portería vertical</div>
</div>

<main class="main">
    <?php foreach ($posts as $post): ?>
        <article class="main-article">
            <?php echo $post->options['tiktok'] ?>
            <div>
                <h2>
                    <a href="/<?php echo $view->escape($post->url, 'path') ?>"><?php echo $view->escape($post->title) ?></a>
                </h2>
                <a href="/<?php echo $view->escape($post->url, 'path') ?>">Ver más →</a>
            </div>
            <div class="article-bg">
                <img src="/assets/images/bg.svg" />
            </div>
        </article>
    <?php endforeach ?>
</main>

<?php $view['slots']->start('scripts') ?>
<?php $view['slots']->stop() ?>
