<!doctype html>
<html lang="es" class="no-js" itemscope itemtype="http://schema.org/Webpage">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta name="author" content="UEStudio">
        <meta name="referrer" content="same-origin">

        <!-- Place this data between the <head> tags of your website -->
        <title><?php $view['slots']->output('title', $GLOBALS['config']['web_name']) ?> ~ La Portería Vertical | Marca</title>

        <!-- Schema.org markup (Google) -->
        <meta itemprop="name" content="<?php $view['slots']->output('title', $GLOBALS['config']['web_name']) ?>">
        <meta itemprop="description" content="<?php $view['slots']->output('google', 'SDescubre toda la información sobre la Eurocopa 2020 de la mano de TikTok #Euro2020 #TikTokFootballAcademy') ?>">
        <meta itemprop="image" content="<?php $view['slots']->output('image', 'https://laporteriavertical.marca.com/assets/images/RRSS.png') ?>">

        <!-- Twitter Card markup-->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="@uestudio_es">
        <meta name="twitter:title" content="<?php $view['slots']->output('title', $GLOBALS['config']['web_name']) ?>">
        <meta name="twitter:description" content="<?php $view['slots']->output('facebook', 'SDescubre toda la información sobre la Eurocopa 2020 de la mano de TikTok #Euro2020 #TikTokFootballAcademy') ?>">
        <meta name="twitter:creator" content="@uestudio_es">
        <!-- Twitter summary card with large image must be at least 280x150px -->
        <meta name="twitter:image" content="<?php $view['slots']->output('image', 'https://laporteriavertical.marca.com/assets/images/RRSS.png') ?>">
        <meta name="twitter:image:alt" content="<?php $view['slots']->output('title', $GLOBALS['config']['web_name']) ?>">

        <!-- Open Graph markup (Facebook, Pinterest) -->
        <meta property="og:title" content="<?php $view['slots']->output('title', $GLOBALS['config']['web_name']) ?>">
        <meta property="og:type" content="article">
        <meta property="og:url" content="https://laporteriavertical.marca.com<?php echo $uri ?>">
        <meta property="og:image" content="<?php $view['slots']->output('image', 'https://laporteriavertical.marca.com/assets/images/RRSS.png') ?>">
        <meta property="og:description" content="<?php $view['slots']->output('facebook', 'SDescubre toda la información sobre la Eurocopa 2020 de la mano de TikTok #Euro2020 #TikTokFootballAcademy') ?>">
        <meta property="og:site_name" content="<?php echo $GLOBALS['config']['web_name'] ?>">

        <link rel="canonical" href="https://laporteriavertical.marca.com<?php echo $uri ?>">

        <?php $view['slots']->output('trust') ?>

        <link rel="apple-touch-icon" href="/apple-touch-icon.png">

        <link href="/assets/css/main.css?v2" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://use.typekit.net/jrv3bef.css">

        <?php $view['slots']->output('styles') ?>

        <!--[if lt IE 9]>
            <script src="http://estaticos.elmundo.es/em/js/html5.js"></script>
        <![endif]-->

        <script src="//e00-apps-ue.uecdn.es/tms/js/tms-branded.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <script type="text/javascript" language="javascript" src="https://e00-ue.uecdn.es/cookies/js/policy_v4.js"></script>
        <script type="text/javascript">window.gdprAppliesGlobally=true;(function(){function a(e){if(!window.frames[e]){if(document.body&&document.body.firstChild){var t=document.body;var n=document.createElement("iframe");n.style.display="none";n.name=e;n.title=e;t.insertBefore(n,t.firstChild)} 
      else{setTimeout(function(){a(e)},5)}}}function e(n,r,o,c,s){function e(e,t,n,a){if(typeof n!=="function"){return}if(!window[r]){window[r]=[]}var i=false;if(s){i=s(e,t,n)}if(!i){window[r].push({command:e,parameter:t,callback:n,version:a})}}e.stub=true;function t(a){if(!window[n]||window[n].stub!==true){return}if(!a.data){return} 
        var i=typeof a.data==="string";var e;try{e=i?JSON.parse(a.data):a.data}catch(t){return}if(e[o]){var r=e[o];window[n](r.command,r.parameter,function(e,t){var n={};n[c]={returnValue:e,success:t,callId:r.callId};a.source.postMessage(i?JSON.stringify(n):n,"*")},r.version)}} 
        if(typeof window[n]!=="function"){window[n]=e;if(window.addEventListener){window.addEventListener("message",t,false)}else{window.attachEvent("onmessage",t)}}}e("__tcfapi","__tcfapiBuffer","__tcfapiCall","__tcfapiReturn");a("__tcfapiLocator");(function(e,tgt){ 
        var t=document.createElement("script");t.id="spcloader";t.type="text/javascript";t.async=true;t.src="https://sdk.privacy-center.org/"+e+"/loader.js?target_type=notice&target="+tgt;t.charset="utf-8";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n)})("178119d0-5586-4a4c-953e-04aaf9ac0994","DC8decYU")})();</script>
    </head>
    <body class="<?php $view['slots']->output('section') ?>">
        <header class="header down">
            <div class="logos">
                <a href="https://www.marca.com/" class="marca" target="_blank">
                    <img src="/assets/images/marca_black.svg" alt="Marca" />
                </a>
            </div>
            <div class="logo">
                <a href="/">
                    <img src="/assets/images/logo2.png" alt="La portería digital"/>
                </a>
            </div>
            <div class="menu">
                <a href="https://www.tiktok.com/" target="_blank" rel="nofollow noopener">
                    <img src="/assets/images/tiktok.png" alt="TikTok" />
                </a>
            </div>
        </header>
        
        <?php $view['slots']->output('_content') ?>
        
        <footer class="footer">
            <div class="footer-content">
                <a href="https://www.tiktok.com/" target="_blank" rel="nofollow noopener">
                    <img src="/assets/images/tiktok.png" alt="TikTok" />
                </a>
                <p>Este proyecto ha sido desarrollado por <a href="http://uestudio.es/" target="_blank">UE Studio</a>, firma creativa de branded content y marketing de contenidos de Unidad Editorial</p>
            </div>
        </footer>

        <!-- JS -->
        <script src="/assets/js/bundle.min.js"></script>
        <script src="https://player.vimeo.com/api/player.js"></script>
        <!--<script src="assets/js/embed.js"></script>-->
        <script src="/assets/js/body.js"></script>

        <?php $view['slots']->output('scripts') ?>

        <script>
            TMSBottom();

            var _sf_async_config = _sf_async_config || {};
            /** CONFIGURATION START **/
            _sf_async_config.uid = 52682;
            _sf_async_config.domain = '<?php echo $view->escape($domain) ?>';
            _sf_async_config.useCanonical = true;
            _sf_async_config.sections = 'UEstudio';
            _sf_async_config.authors = '<?php echo $view->escape($GLOBALS['config']['web_name']) ?>';
            /** CONFIGURATION END **/
            (function() {
                function loadChartbeat() {
                    window._sf_endpt = (new Date()).getTime();
                    var e = document.createElement('script');
                    e.setAttribute('language', 'javascript');
                    e.setAttribute('type', 'text/javascript');
                    e.setAttribute('src', '//static.chartbeat.com/js/chartbeat.js');
                    document.body.appendChild(e);
                }
                var oldonload = window.onload;
                window.onload = (typeof window.onload != 'function') ?
                    loadChartbeat : function() {
                        oldonload();
                        loadChartbeat();
                    };
            })();
        </script>
    </body>
</html>
