<div class="share">
    <ul>
        <li>
            <a href="http://www.facebook.com/sharer.php?u=<?php echo $view->escape('https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] . '?cid=SMBOSO22801&s_kw=BC-facebook', 'url') ?>" target="_blank" rel="nofollow" onclick="gtag('event', 'Social', {'event_category': 'Facebook'});envioEventoRedSocial('facebook');" title="Compártelo en Facebook" itemprop="sameAs">
                <svg version="1.1" id="svgFacebook" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
                    <path fill="#4BD8E0" d="M384,0.1L317.6,0C243,0,194.8,49.5,194.8,126v58.1H128c-5.8,0-10.4,4.7-10.4,10.4v84.2
                    c0,5.8,4.7,10.4,10.4,10.4h66.8v212.4c0,5.8,4.7,10.4,10.4,10.4h87.1c5.8,0,10.4-4.7,10.4-10.4V289.2h78.1c5.8,0,10.4-4.7,10.4-10.4
                    l0-84.2c0-2.8-1.1-5.4-3.1-7.4c-2-2-4.6-3.1-7.4-3.1h-78.1v-49.2c0-23.7,5.6-35.7,36.5-35.7l44.7,0c5.8,0,10.4-4.7,10.4-10.4V10.5
                    C394.4,4.8,389.7,0.1,384,0.1L384,0.1z"/>
                </svg>
            </a>
        </li>
        <li>
            <a href="https://twitter.com/intent/tweet?url=<?php echo $view->escape('https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] . '?cid=SMBOSO22801&s_kw=BC-twitter', 'url') ?>&amp;text=<?php $view['slots']->output('twitter', urlencode('Si eres una pyme o autónomo súmate a #CompatiendoConocimiento')) ?>&amp;wrap_links=true" target="_blank" rel="nofollow" onclick="gtag('event', 'Social', {'event_category': 'Twitter'});envioEventoRedSocial('twitter');" title="Compártelo en Twitter" itemprop="sameAs">
                <svg version="1.1" id="svgTwitter" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512.1 415.9" style="enable-background:new 0 0 512.1 415.9;" xml:space="preserve">
                    <path fill="#4BD8E0" d="M512.1,49.3c-19.1,8.5-39.5,14.1-60.3,16.5C473.7,52.7,490.1,32,498,7.7c-20.6,12.2-43.2,20.8-66.7,25.5
                    C391.5-9.1,325-11.1,282.7,28.7c-27.2,25.6-38.8,63.8-30.4,100.2C167.8,124.7,89.2,84.8,35.8,19.2c-9.4,16-14.3,34.2-14.2,52.8
                    c0,35.1,17.5,67.9,46.7,87.4c-16.7-0.6-33-5.1-47.6-13.2v1.3c0,50,35.2,93,84.2,103c-9,2.5-18.3,3.7-27.7,3.7
                    c-6.7,0-13.3-0.7-19.8-2c13.7,42.8,53.2,72.1,98.1,72.9c-37.2,29.2-83.1,45-130.4,44.9c-8.4,0-16.8-0.5-25.1-1.4
                    c48,30.9,103.9,47.4,161,47.3c193.2,0,298.8-160,298.8-298.8l-0.4-13.6C480.1,88.8,498,70.4,512.1,49.3z"/>
                </svg>
            </a>
        </li>
    </ul>
</div>